name: Deploy to Azure App Service

on:
  push:
    branches:
      - main  # Trigger deployment on push to main branch

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    # Step 1: Checkout the code from the repository
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2

    # Step 2: Set up .NET Core SDK (if applicable for your project)
    - name: 'Set up .NET Core'
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x' # Modify based on your project version

    # Step 3: Build the project (if necessary for .NET-based sites)
    - name: 'Build project'
      run: dotnet build --configuration Release

    # Step 4: Login to Azure
    - name: 'Azure Login'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Step 5: Deploy to Azure App Service
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'your-app-service-name'  # Replace with your Azure App Service name
        package: './newcv/'  # Path to your web app package or directory
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
